# 01_eda_datasets.ipynb

Primer notebook del proyecto **Sistema híbrido para predecir churn de clientes en retail y generar acciones personalizadas de retención mediante IA generativa**.

Objetivos de este notebook:
- Cargar los 3 archivos `.xlsx` de la carpeta `data/raw/`
- Inspeccionar estructura, hojas, columnas y tipos de datos
- Evaluar calidad inicial de datos
- Identificar la mejor base para definir churn y construir el dataset analítico

## 0. Librerías

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
import openpyxl

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
pd.set_option('display.width', 120)

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## 1. Configuración de rutas

Asegúrate de guardar los tres archivos Excel dentro de `data/raw/`.

In [3]:
RAW_PATH = Path('/content/drive/MyDrive/PI_LV/data/raw')
excel_files = sorted(list(RAW_PATH.glob('*.xlsx')))

print('Archivos encontrados:')
for f in excel_files:
    print('-', f.name)

Archivos encontrados:
- 0_PI_Dims-Deuda - ENVIAR.xlsx
- 0_PI_Ventas-2022-2023 - ENVIAR.xlsx
- 0_PI_Ventas-2024-2025 - ENVIAR.xlsx

## 2. Revisar hojas disponibles en cada archivo

In [4]:
excel_sheets = {}

for file in excel_files:
    xls = pd.ExcelFile(file)
    excel_sheets[file.name] = xls.sheet_names
    print(f'\n{file.name}')
    print(xls.sheet_names)

0_PI_Dims-Deuda - ENVIAR.xlsx
['Deudas', 'Dim_Gerencia', 'Dim_UnidadNegocio', 'Dim_TipoGerencia', 'Dim_Procedencia', 'Dim_Producto', 'Dim_Cliente']

0_PI_Ventas-2022-2023 - ENVIAR.xlsx
['Ventas_2023', 'Ventas_2022']

0_PI_Ventas-2024-2025 - ENVIAR.xlsx
['Ventas_2025-2', 'Ventas_2025-1', 'Ventas_2024']

## 3. Cargar las hojas de cada archivo

In [5]:
datasets = {}

for file in excel_files:
    xls = pd.ExcelFile(file)
    datasets[file.stem] = {}

    for sheet in xls.sheet_names:
        df = pd.read_excel(file, sheet_name=sheet)
        datasets[file.stem][sheet] = df
        print(f"{file.name} | {sheet}: {df.shape}")

0_PI_Dims-Deuda - ENVIAR.xlsx | Deudas: (454679, 28)
0_PI_Dims-Deuda - ENVIAR.xlsx | Dim_Gerencia: (8, 2)
0_PI_Dims-Deuda - ENVIAR.xlsx | Dim_UnidadNegocio: (119, 7)
0_PI_Dims-Deuda - ENVIAR.xlsx | Dim_TipoGerencia: (6, 2)
0_PI_Dims-Deuda - ENVIAR.xlsx | Dim_Procedencia: (4, 2)
0_PI_Dims-Deuda - ENVIAR.xlsx | Dim_Producto: (6073, 7)
0_PI_Dims-Deuda - ENVIAR.xlsx | Dim_Cliente: (167550, 25)
0_PI_Ventas-2022-2023 - ENVIAR.xlsx | Ventas_2023: (873613, 31)
0_PI_Ventas-2022-2023 - ENVIAR.xlsx | Ventas_2022: (843446, 31)
0_PI_Ventas-2024-2025 - ENVIAR.xlsx | Ventas_2025-2: (671019, 31)
0_PI_Ventas-2024-2025 - ENVIAR.xlsx | Ventas_2025-1: (583137, 31)
0_PI_Ventas-2024-2025 - ENVIAR.xlsx | Ventas_2024: (1002662, 31)

## 4. Vista rápida de cada dataset

In [6]:
for name, sheet_dict in datasets.items():
    print('='*90)
    print(f'DATASET: {name}')
    print('='*90)

    for sheet_name, df in sheet_dict.items():
        print(f'\nSHEET: {sheet_name}')
        display(df.head())
        print('Columnas:')
        print(df.columns.tolist())
        print('\nTipos de datos:')
        print(df.dtypes)
        print('\n')

==========================================================================================
DATASET: 0_PI_Dims-Deuda - ENVIAR
==========================================================================================

SHEET: Deudas

,Cliente_ID-NEW,Domicilio_ID,Cliente_Dom_ID-NEW,Vendedor_ID,Gerencia_ID,UnidadNegocio_ID,TipoGerencia_ID,Procedencia_ID,Periodo_ID,Documento_ID-NEW,TipoDocumento,FechaEmision,FechaVencimiento,DiasVencimiento,TerminoPago_Resumen,Dias,TerminoPago,Fecha_UltPago,Actualizacion,Moneda,Calificacion,DiasVencimientoMayor,OrdenCalificacion,Saldo,MontoDocumento,Monto_UltPago,Importe_FC,Saldo_FC
0,C138097,01,C138097-01,125,265.0,U111,579,585,2024-02-29,2024351407,FACTURA,2024-02-29,2024-04-29,000-Corriente,Crédito,-60,CREDITO 60 DIAS,NaT,2024-03-05 18:58:46.991,S/,NaN,NaN,99,2497.41,2497.41,0.0,0.0,0.0
1,C138097,01,C138097-01,125,265.0,U111,579,585,2024-02-29,2024351406,FACTURA,2024-02-29,2024-04-29,000-Corriente,Crédito,-60,CREDITO 60 DIAS,NaT,2024-03-05 18:58:46.991,S/,NaN,NaN,99,2022.17,2022.17,0.0,0.0,0.0
2,C062797,01,C062797-01,125,265.0,U111,579,585,2024-02-29,2024351000,FACTURA,2024-02-29,2024-04-29,000-Corriente,Crédito,-60,CREDITO 60 DIAS,NaT,2024-03-05 18:58:46.991,S/,NaN,NaN,99,402.23,402.23,0.0,0.0,0.0
3,C085739,01,C085739-01,125,265.0,U111,579,585,2024-02-29,2024350998,FACTURA,2024-02-29,2024-04-29,000-Corriente,Crédito,-60,CREDITO 60 DIAS,NaT,2024-03-05 18:58:46.991,S/,NaN,NaN,99,6821.04,6821.04,0.0,0.0,0.0
4,C113475,01,C113475-01,125,265.0,U111,579,585,2024-02-29,2024350567,FACTURA,2024-02-29,2024-04-29,000-Corriente,Crédito,-60,CREDITO 60 DIAS,NaT,2024-03-05 18:58:46.991,S/,NaN,NaN,99,4940.45,4940.45,0.0,0.0,0.0

Columnas:
['Cliente_ID-NEW', 'Domicilio_ID', 'Cliente_Dom_ID-NEW', 'Vendedor_ID', 'Gerencia_ID', 'UnidadNegocio_ID', 'TipoGerencia_ID', 'Procedencia_ID', 'Periodo_ID', 'Documento_ID-NEW', 'TipoDocumento', 'FechaEmision', 'FechaVencimiento', 'DiasVencimiento', 'TerminoPago_Resumen', 'Dias', 'TerminoPago', 'Fecha_UltPago', 'Actualizacion', 'Moneda', 'Calificacion', 'DiasVencimientoMayor', 'OrdenCalificacion', 'Saldo', 'MontoDocumento', 'Monto_UltPago', 'Importe_FC', 'Saldo_FC']

Tipos de datos:
Cliente_ID-NEW                  object
Domicilio_ID                    object
Cliente_Dom_ID-NEW              object
Vendedor_ID                      int64
Gerencia_ID                    float64
UnidadNegocio_ID                object
TipoGerencia_ID                  int64
Procedencia_ID                   int64
Periodo_ID              datetime64[ns]
Documento_ID-NEW                 int64
TipoDocumento                   object
FechaEmision            datetime64[ns]
FechaVencimiento        datetime64[ns]
DiasVencimiento                 object
TerminoPago_Resumen             object
Dias                             int64
TerminoPago                     object
Fecha_UltPago           datetime64[ns]
Actualizacion           datetime64[ns]
Moneda                          object
Calificacion                    object
DiasVencimientoMayor            object
OrdenCalificacion                int64
Saldo                          float64
MontoDocumento                 float64
Monto_UltPago                  float64
Importe_FC                     float64
Saldo_FC                       float64
dtype: object



SHEET: Dim_Gerencia

   Gerencia_ID                        Gerencia
0         2144    ROMANO FIERRO MANUEL ALBERTO
1         4148  HERBOZO IBAÑEZ GUSTAVO ENRIQUE
2          777                  INTERNACIONAL
3          266                 NORTE GERENCIA
4         1990        CENTRO ORIENTE GERENCIA

Columnas:
['Gerencia_ID', 'Gerencia']

Tipos de datos:
Gerencia_ID     int64
Gerencia       object
dtype: object



SHEET: Dim_UnidadNegocio

,UnidadNegocio_ID,UnidadNegocio,GrupoUnidadNegocio,DescripcionPadre,Canal,Subcanal,Territorio
0,U252,AREQUIPA,ALMACENES/DISTRIBUIDORAS,AREQUIPA,DETALLE,VISTONY,SUCURSALES
1,U370,CHIMBOTE-LPC,LINEA DE PRODUCTO COMPLEMENTARIO,CHIMBOTE,DETALLE,LPC,SUCURSALES
2,U308,ICA-HOME CARE,HOME CARE,ICA,DETALLE,HOME CARE,SUCURSALES
3,U281,AREQUIPA-LPC,LINEA PRODUCTO COMPLEMENTARIO,AREQUIPA,DETALLE,LPC,SUCURSALES
4,U323,AYACUCHO-HOME CARE,HOME CARE,AYACUCHO,DETALLE,HOME CARE,SUCURSALES

Columnas:
['UnidadNegocio_ID', 'UnidadNegocio', 'GrupoUnidadNegocio', 'DescripcionPadre', 'Canal', 'Subcanal', 'Territorio']

Tipos de datos:
UnidadNegocio_ID      object
UnidadNegocio         object
GrupoUnidadNegocio    object
DescripcionPadre      object
Canal                 object
Subcanal              object
Territorio            object
dtype: object



SHEET: Dim_TipoGerencia

   TipoGerencia_ID            TipoGerencia
0              581  GERENCIA INTERNACIONAL
1              580            GERENCIA B2B
2              579            GERENCIA B2C
3             2124    RELACIONADA GERENCIA
4             2123        OFICINA GERENCIA

Columnas:
['TipoGerencia_ID', 'TipoGerencia']

Tipos de datos:
TipoGerencia_ID     int64
TipoGerencia       object
dtype: object



SHEET: Dim_Procedencia

   Procedencia_ID            Procedencia
0             585              NACIONAL
1             586         INTERNACIONAL
2            2552   NACIONAL RELACIONADA
3            2556                 OTROS

Columnas:
['Procedencia_ID', 'Procedencia']

Tipos de datos:
Procedencia_ID     int64
Procedencia       object
dtype: object



SHEET: Dim_Producto

  Producto_ID-NEW UnidadMedida        GrupoProducto    Estado Categoria Linea  Galonaje
0         P000002          UND  MATERIALES LIMPIEZA  Inactivo       NaN   NaN       0.0
1         P000003          UND  MATERIALES LIMPIEZA  Inactivo       NaN   NaN       0.0
2         P000004          UND     MAT PUBLICITARIO  Inactivo     OTROS   NaN       0.0
3         P000005          UND     MAT PUBLICITARIO  Inactivo     OTROS   NaN       0.0
4         P000006          UND     MAT PUBLICITARIO  Inactivo     OTROS   NaN       0.0

Columnas:
['Producto_ID-NEW', 'UnidadMedida', 'GrupoProducto', 'Estado', 'Categoria', 'Linea', 'Galonaje']

Tipos de datos:
Producto_ID-NEW     object
UnidadMedida        object
GrupoProducto       object
Estado              object
Categoria           object
Linea               object
Galonaje           float64
dtype: object



SHEET: Dim_Cliente

,Cliente_ID-NEW,Domicilio_ID,Cliente_Dom_ID-NEW,Cliente_Categoria,FechaCreacionCliente,Giro_Negocio,Actividad,Distrito,Provincia,Departamento,Pais,Ubigeo,Linea_Credito,Vendedor_ID,Dia_Ruta,Dias_Entrega,Longitud,Latitud,Geolocalizado,CondicionPago,Estado,CategoriaPotencial,TipoIdentificacion,Actualizado,Saldo
0,K000002,01,K000002-01,D,2025-05-07,TALLER DE AUTOS CON VTA DE LUBRICANTES,MECANICAS,LURIGANCHO,LIMA,LIMA,Peru,150118,0.0,1831.0,LUNES,1,-76.88895416259766,-12.007922172546387,Geolocalizado,Contado,Activo,D,DNI,0,0.0
1,K000003,02,K000003-02,D,2022-06-10,ESTACIONES DE SERVICIO,COMERCIO MINORISTA,CASTILLA,PIURA,PIURA,Peru,200104,0.0,291.0,SABADO,1,-80.63176936,-5.18608571,Geolocalizado,CREDITO 45 DIAS,Activo,D,RUC,0,0.0
2,C000004,01,C000004-01,D,2021-11-24,LUBRICENTRO TALLER DE MOTOS,MECANICAS,PUEBLO NUEVO,CHINCHA,ICA,Peru,110207,0.0,396.0,LUNES,4,-76.12553405761719,-13.405879974365234,Geolocalizado,Contado,Activo,D,DNI,0,600.0
3,C000005,01,C000005-01,D,2021-03-29,CARGA,TRANSPORTE,SAN BORJA,LIMA,LIMA,Peru,150130,0.0,1949.0,DOMINGO,1,0,0,No Geolocalizado,Contado,Activo,D,RUC,0,0.0
4,K000006,01,K000006-01,D,2021-09-20,TALLER DE AUTOS CON VTA DE LUBRICANTES,MECANICAS,SAN MARTIN DE PORRES,LIMA,LIMA,Peru,150135,0.0,1339.0,DOMINGO,1,-77.0855712890625,-12.021695137023926,Geolocalizado,CREDITO 45 DIAS,Activo,D,RUC,0,0.0

Columnas:
['Cliente_ID-NEW', 'Domicilio_ID', 'Cliente_Dom_ID-NEW', 'Cliente_Categoria', 'FechaCreacionCliente', 'Giro_Negocio', 'Actividad', 'Distrito', 'Provincia', 'Departamento', 'Pais', 'Ubigeo', 'Linea_Credito', 'Vendedor_ID', 'Dia_Ruta', 'Dias_Entrega', 'Longitud', 'Latitud', 'Geolocalizado', 'CondicionPago', 'Estado', 'CategoriaPotencial', 'TipoIdentificacion', 'Actualizado', 'Saldo']

Tipos de datos:
Cliente_ID-NEW                  object
Domicilio_ID                    object
Cliente_Dom_ID-NEW              object
Cliente_Categoria               object
FechaCreacionCliente    datetime64[ns]
Giro_Negocio                    object
Actividad                       object
Distrito                        object
Provincia                       object
Departamento                    object
Pais                            object
Ubigeo                          object
Linea_Credito                  float64
Vendedor_ID                    float64
Dia_Ruta                        object
Dias_Entrega                     int64
Longitud                        object
Latitud                         object
Geolocalizado                   object
CondicionPago                   object
Estado                          object
CategoriaPotencial              object
TipoIdentificacion              object
Actualizado                      int64
Saldo                          float64
dtype: object


==========================================================================================
DATASET: 0_PI_Ventas-2022-2023 - ENVIAR
==========================================================================================

SHEET: Ventas_2023

,Documento,Documento_ID-NEW,FechaEmision,TipoVenta,TerminoPago,TerminoPago_Resumen,Vendedor_ID,Gerencia_ID,UnidadNegocio_ID,TipoGerencia_ID,Procedencia_ID,Producto_ID-NEW,Cliente_ID-NEW,Domicilio_ID,Cliente_Dom_ID-NEW,Indicador_Impuesto,Moneda,Tipo_Cambio,Descuento_Porc,Almacen,Motivo_Descuento,FechaVencimiento,Galones,Cantidad,Total_con_Impuesto,Total_sin_Impuesto,Total_Costo,Total_Promocion,Total_Promocion_PV,Total_Total_Costo,Descuento
0,Factura,2023000002,2023-12-31,Venta Neta,Contado,Contado,1349,265,U111,579,585,P004897,C084221,1,C084221-01,IGV,S/,3.713,10.0,AN001,NINGUNO,2023-12-31,6.336,2,838.79,710.84,296.910000,0.00,0.0,296.910000,78.9820
1,Factura,2023000003,2023-12-31,Venta Neta,Contado,Contado,388,266,U211,579,585,P006017,C134166,1,C134166-01,IGV,S/,3.713,5.0,CH001,NINGUNO,2023-12-31,55.000,1,2657.82,2252.39,1268.260000,0.00,0.0,1268.260000,118.5470
2,Factura,2023000003,2023-12-31,Promoción,Contado,Contado,388,266,U211,579,585,P004933,C134166,1,C134166-01,EXE_IGV,S/,3.713,0.0,CH001,NINGUNO,2023-12-31,5.000,1,244.80,0.00,0.000000,107.59,244.8,107.590000,0.0000
3,Factura,2023000003,2023-12-31,Promoción,Contado,Contado,388,266,U211,579,585,P006026,C134166,1,C134166-01,EXE_IGV,S/,3.713,0.0,CH001,NINGUNO,2023-12-31,5.000,1,244.80,0.00,0.000000,111.99,244.8,111.990000,0.0000
4,Factura,2023000004,2023-12-31,Venta Neta,Contado,Contado,950,1990,U256,579,585,P006043,C089151,1,C089151-01,IGV,S/,3.713,14.0,LM001,NINGUNO,2023-12-31,18.000,3,113.77,96.41,58.629999,0.00,0.0,58.629999,15.6954

Columnas:
['Documento', 'Documento_ID-NEW', 'FechaEmision', 'TipoVenta', 'TerminoPago', 'TerminoPago_Resumen', 'Vendedor_ID', 'Gerencia_ID', 'UnidadNegocio_ID', 'TipoGerencia_ID', 'Procedencia_ID', 'Producto_ID-NEW', 'Cliente_ID-NEW', 'Domicilio_ID', 'Cliente_Dom_ID-NEW', 'Indicador_Impuesto', 'Moneda', 'Tipo_Cambio', 'Descuento_Porc', 'Almacen', 'Motivo_Descuento', 'FechaVencimiento', 'Galones', 'Cantidad', 'Total_con_Impuesto', 'Total_sin_Impuesto', 'Total_Costo', 'Total_Promocion', 'Total_Promocion_PV', 'Total_Total_Costo', 'Descuento']

Tipos de datos:
Documento                      object
Documento_ID-NEW                int64
FechaEmision           datetime64[ns]
TipoVenta                      object
TerminoPago                    object
TerminoPago_Resumen            object
Vendedor_ID                     int64
Gerencia_ID                     int64
UnidadNegocio_ID               object
TipoGerencia_ID                 int64
Procedencia_ID                  int64
Producto_ID-NEW                object
Cliente_ID-NEW                 object
Domicilio_ID                    int64
Cliente_Dom_ID-NEW             object
Indicador_Impuesto             object
Moneda                         object
Tipo_Cambio                   float64
Descuento_Porc                float64
Almacen                        object
Motivo_Descuento               object
FechaVencimiento       datetime64[ns]
Galones                       float64
Cantidad                        int64
Total_con_Impuesto            float64
Total_sin_Impuesto            float64
Total_Costo                   float64
Total_Promocion               float64
Total_Promocion_PV            float64
Total_Total_Costo             float64
Descuento                     float64
dtype: object



SHEET: Ventas_2022

,Documento,Documento_ID-NEW,FechaEmision,TipoVenta,TerminoPago,TerminoPago_Resumen,Vendedor_ID,Gerencia_ID,UnidadNegocio_ID,TipoGerencia_ID,Procedencia_ID,Producto_ID-NEW,Cliente_ID-NEW,Domicilio_ID,Cliente_Dom_ID-NEW,Indicador_Impuesto,Moneda,Tipo_Cambio,Descuento_Porc,Almacen,Motivo_Descuento,FechaVencimiento,Galones,Cantidad,Total_con_Impuesto,Total_sin_Impuesto,Total_Costo,Total_Promocion,Total_Promocion_PV,Total_Total_Costo,Descuento
0,Factura,2022000002,2022-12-31,Venta Neta,CREDITO 60 DIAS,Crédito,129,266,U216,579,585,P005942,C141747,1,C141747-01,IGV,S/,3.808,0.0,TR001,NaN,2023-03-01,55.0000,1.0,2742.51,2324.16,1494.31,0.00,0.000000,1494.31,0.00
1,Factura,2022000002,2022-12-31,Promoción,CREDITO 60 DIAS,Crédito,129,266,U216,579,585,P006026,C141747,1,C141747-01,EXE_IGV,S/,3.808,0.0,TR001,NaN,2023-03-01,5.0000,1.0,245.94,0.00,0.00,138.03,245.940000,138.03,0.00
2,Factura,2022000002,2022-12-31,Promoción,CREDITO 60 DIAS,Crédito,129,266,U216,579,585,P004898,C141747,1,C141747-01,EXE_IGV,S/,3.808,0.0,TR001,NaN,2023-03-01,2.5000,1.0,125.43,0.00,0.00,70.03,125.431326,70.03,0.00
3,Factura,2022000003,2022-12-31,Venta Neta,CREDITO 30 DIAS,Crédito,129,266,U216,579,585,P006028,C134704,1,C134704-01,IGV,S/,3.808,25.0,TR001,NaN,2023-01-30,500.0000,100.0,16582.25,14052.75,11408.46,0.00,0.000000,11408.46,4684.25
4,Factura,2022000004,2022-12-31,Venta Neta,Contado,Contado,129,266,U216,579,585,P006023,C149935,1,C149935-01,IGV,S/,3.808,0.0,TR001,NaN,2022-12-31,25.3632,8.0,2066.23,1751.04,721.41,0.00,0.000000,721.41,0.00

Columnas:
['Documento', 'Documento_ID-NEW', 'FechaEmision', 'TipoVenta', 'TerminoPago', 'TerminoPago_Resumen', 'Vendedor_ID', 'Gerencia_ID', 'UnidadNegocio_ID', 'TipoGerencia_ID', 'Procedencia_ID', 'Producto_ID-NEW', 'Cliente_ID-NEW', 'Domicilio_ID', 'Cliente_Dom_ID-NEW', 'Indicador_Impuesto', 'Moneda', 'Tipo_Cambio', 'Descuento_Porc', 'Almacen', 'Motivo_Descuento', 'FechaVencimiento', 'Galones', 'Cantidad', 'Total_con_Impuesto', 'Total_sin_Impuesto', 'Total_Costo', 'Total_Promocion', 'Total_Promocion_PV', 'Total_Total_Costo', 'Descuento']

Tipos de datos:
Documento                      object
Documento_ID-NEW                int64
FechaEmision           datetime64[ns]
TipoVenta                      object
TerminoPago                    object
TerminoPago_Resumen            object
Vendedor_ID                     int64
Gerencia_ID                     int64
UnidadNegocio_ID               object
TipoGerencia_ID                 int64
Procedencia_ID                  int64
Producto_ID-NEW                object
Cliente_ID-NEW                 object
Domicilio_ID                    int64
Cliente_Dom_ID-NEW             object
Indicador_Impuesto             object
Moneda                         object
Tipo_Cambio                   float64
Descuento_Porc                float64
Almacen                        object
Motivo_Descuento              float64
FechaVencimiento       datetime64[ns]
Galones                       float64
Cantidad                      float64
Total_con_Impuesto            float64
Total_sin_Impuesto            float64
Total_Costo                   float64
Total_Promocion               float64
Total_Promocion_PV            float64
Total_Total_Costo             float64
Descuento                     float64
dtype: object


==========================================================================================
DATASET: 0_PI_Ventas-2024-2025 - ENVIAR
==========================================================================================

SHEET: Ventas_2025-2

,Documento,Documento_ID-NEW,FechaEmision,TipoVenta,TerminoPago,TerminoPago_Resumen,Vendedor_ID,Gerencia_ID,UnidadNegocio_ID,TipoGerencia_ID,Procedencia_ID,Producto_ID-NEW,Cliente_ID-NEW,Domicilio_ID,Cliente_Dom_ID-NEW,Indicador_Impuesto,Moneda,Tipo_Cambio,Descuento_Porc,Almacen,Motivo_Descuento,FechaVencimiento,Galones,Cantidad,Total_con_Impuesto,Total_sin_Impuesto,Total_Costo,Total_Promocion,Total_Promocion_PV,Total_Total_Costo,Descuento
0,Factura,2025234158,2025-12-31,Transferencia Gratuita,TRANSFERENCIA GRATUITA,Crédito,1534,265,U304,579,585,P004185,R005070,01,R005070-01,IGV,S/,3.369,0.00,NaN,NINGUNO,2025-12-31,0.000000,0,33.42,28.32,0.00,0.00,0.00,0.00,0.0000
1,Factura,2025234159,2025-12-31,Venta Neta,Contado,Contado,2028,265,U111,579,585,P002362,C058982,01,C058982-01,IGV_FISE,S/,3.369,24.24,AN001,NINGUNO,2025-12-31,250.000000,50,9965.06,8444.97,4584.11,0.00,0.00,4584.11,2702.0328
2,Factura,2025234160,2025-12-31,Promoción,Contado,Contado,2018,265,U304,579,585,P004313,R131370,01,R131370-01,EXE_IGV,S/,3.369,0.00,AN001,NINGUNO,2025-12-31,0.317200,4,12.80,0.00,0.00,6.63,12.80,6.63,0.0000
3,Factura,2025234160,2025-12-31,Venta Neta,Contado,Contado,2018,265,U304,579,585,P004140,R131370,01,R131370-01,IGV,S/,3.369,15.00,AN001,NINGUNO,2025-12-31,3.935952,4,28.08,23.80,23.25,0.00,0.00,23.25,4.2000
4,Factura,2025234160,2025-12-31,Promoción,Contado,Contado,2018,265,U304,579,585,P002362,R131370,01,R131370-01,EXE_IGV,S/,3.369,0.00,AN001,NINGUNO,2025-12-31,0.000000,16,1.28,0.00,0.00,0.84,1.28,0.84,0.0000

Columnas:
['Documento', 'Documento_ID-NEW', 'FechaEmision', 'TipoVenta', 'TerminoPago', 'TerminoPago_Resumen', 'Vendedor_ID', 'Gerencia_ID', 'UnidadNegocio_ID', 'TipoGerencia_ID', 'Procedencia_ID', 'Producto_ID-NEW', 'Cliente_ID-NEW', 'Domicilio_ID', 'Cliente_Dom_ID-NEW', 'Indicador_Impuesto', 'Moneda', 'Tipo_Cambio', 'Descuento_Porc', 'Almacen', 'Motivo_Descuento', 'FechaVencimiento', 'Galones', 'Cantidad', 'Total_con_Impuesto', 'Total_sin_Impuesto', 'Total_Costo', 'Total_Promocion', 'Total_Promocion_PV', 'Total_Total_Costo', 'Descuento']

Tipos de datos:
Documento                      object
Documento_ID-NEW                int64
FechaEmision           datetime64[ns]
TipoVenta                      object
TerminoPago                    object
TerminoPago_Resumen            object
Vendedor_ID                     int64
Gerencia_ID                     int64
UnidadNegocio_ID               object
TipoGerencia_ID                 int64
Procedencia_ID                  int64
Producto_ID-NEW                object
Cliente_ID-NEW                 object
Domicilio_ID                   object
Cliente_Dom_ID-NEW             object
Indicador_Impuesto             object
Moneda                         object
Tipo_Cambio                   float64
Descuento_Porc                float64
Almacen                        object
Motivo_Descuento               object
FechaVencimiento       datetime64[ns]
Galones                       float64
Cantidad                        int64
Total_con_Impuesto            float64
Total_sin_Impuesto            float64
Total_Costo                   float64
Total_Promocion               float64
Total_Promocion_PV            float64
Total_Total_Costo             float64
Descuento                     float64
dtype: object



SHEET: Ventas_2025-1

,Documento,Documento_ID-NEW,FechaEmision,TipoVenta,TerminoPago,TerminoPago_Resumen,Vendedor_ID,Gerencia_ID,UnidadNegocio_ID,TipoGerencia_ID,Procedencia_ID,Producto_ID-NEW,Cliente_ID-NEW,Domicilio_ID,Cliente_Dom_ID-NEW,Indicador_Impuesto,Moneda,Tipo_Cambio,Descuento_Porc,Almacen,Motivo_Descuento,FechaVencimiento,Galones,Cantidad,Total_con_Impuesto,Total_sin_Impuesto,Total_Costo,Total_Promocion,Total_Promocion_PV,Total_Total_Costo,Descuento
0,Factura,2025000002,2025-06-30,Venta Neta,CREDITO 60 DIAS,Crédito,226,267,U301,579,585,P004204,C084376,1,C084376-01,IGV,S/,3.552,0.0,AN001,NINGUNO,2025-08-29,4.7520,3,452.62,383.58,173.090001,0.0,0.0,173.090001,0.0000
1,Factura,2025000003,2025-06-30,Venta Neta,CREDITO 60 DIAS,Crédito,226,267,U301,579,585,P002358,C084376,1,C084376-01,IGV,S/,3.552,8.0,AN001,NINGUNO,2025-08-29,2.9568,2,273.14,231.47,119.370000,0.0,0.0,119.370000,20.1280
2,Factura,2025000003,2025-06-30,Venta Neta,CREDITO 60 DIAS,Crédito,226,267,U301,579,585,P004282,C084376,1,C084376-01,IGV,S/,3.552,4.0,AN001,NINGUNO,2025-08-29,2.8152,3,285.47,241.92,84.770001,0.0,0.0,84.770001,10.0800
3,Factura,2025000003,2025-06-30,Venta Neta,CREDITO 60 DIAS,Crédito,226,267,U301,579,585,P004349,C084376,1,C084376-01,IGV,S/,3.552,7.0,AN001,NINGUNO,2025-08-29,0.8280,3,270.39,229.14,79.809999,0.0,0.0,79.809999,17.2473
4,Factura,2025000004,2025-06-30,Venta Neta,PAGO ADELANTADO,Contado,226,267,U301,579,585,P004204,C139073,1,C139073-01,IGV,S/,3.552,0.0,AN001,NINGUNO,2025-06-30,1.5840,1,143.70,121.78,57.690000,0.0,0.0,57.690000,0.0000

Columnas:
['Documento', 'Documento_ID-NEW', 'FechaEmision', 'TipoVenta', 'TerminoPago', 'TerminoPago_Resumen', 'Vendedor_ID', 'Gerencia_ID', 'UnidadNegocio_ID', 'TipoGerencia_ID', 'Procedencia_ID', 'Producto_ID-NEW', 'Cliente_ID-NEW', 'Domicilio_ID', 'Cliente_Dom_ID-NEW', 'Indicador_Impuesto', 'Moneda', 'Tipo_Cambio', 'Descuento_Porc', 'Almacen', 'Motivo_Descuento', 'FechaVencimiento', 'Galones', 'Cantidad', 'Total_con_Impuesto', 'Total_sin_Impuesto', 'Total_Costo', 'Total_Promocion', 'Total_Promocion_PV', 'Total_Total_Costo', 'Descuento']

Tipos de datos:
Documento                      object
Documento_ID-NEW                int64
FechaEmision           datetime64[ns]
TipoVenta                      object
TerminoPago                    object
TerminoPago_Resumen            object
Vendedor_ID                     int64
Gerencia_ID                     int64
UnidadNegocio_ID               object
TipoGerencia_ID                 int64
Procedencia_ID                  int64
Producto_ID-NEW                object
Cliente_ID-NEW                 object
Domicilio_ID                    int64
Cliente_Dom_ID-NEW             object
Indicador_Impuesto             object
Moneda                         object
Tipo_Cambio                   float64
Descuento_Porc                float64
Almacen                        object
Motivo_Descuento               object
FechaVencimiento       datetime64[ns]
Galones                       float64
Cantidad                        int64
Total_con_Impuesto            float64
Total_sin_Impuesto            float64
Total_Costo                   float64
Total_Promocion               float64
Total_Promocion_PV            float64
Total_Total_Costo             float64
Descuento                     float64
dtype: object



SHEET: Ventas_2024

,Documento,Documento_ID-NEW,FechaEmision,TipoVenta,TerminoPago,TerminoPago_Resumen,Vendedor_ID,Gerencia_ID,UnidadNegocio_ID,TipoGerencia_ID,Procedencia_ID,Producto_ID-NEW,Cliente_ID-NEW,Domicilio_ID,Cliente_Dom_ID-NEW,Indicador_Impuesto,Moneda,Tipo_Cambio,Descuento_Porc,Almacen,Motivo_Descuento,FechaVencimiento,Galones,Cantidad,Total_con_Impuesto,Total_sin_Impuesto,Total_Costo,Total_Promocion,Total_Promocion_PV,Total_Total_Costo,Descuento
0,Factura,2024000002,2024-12-31,Promoción,Contado,Contado,1956,265,U111,579,585,P004356,C144814,1,C144814-01,EXE_IGV,S/,3.77,0.0,AN001,NINGUNO,2024-12-31,30.0000,5,164.85,0.00,0.000000,103.59,164.85,103.590000,0.00000
1,Factura,2024000002,2024-12-31,Venta Neta,Contado,Contado,1956,265,U111,579,585,P004356,C144814,1,C144814-01,IGV,S/,3.77,0.0,AN001,NINGUNO,2024-12-31,90.0000,15,583.57,494.55,310.780005,0.00,0.00,310.780005,0.00000
2,Factura,2024000003,2024-12-31,Venta Neta,Contado,Contado,1143,265,U111,579,585,P002569,C077502,1,C077502-01,IGV,S/,3.77,11.8,AN001,NINGUNO,2024-12-31,1.7088,1,111.91,94.84,48.480000,0.00,0.00,48.480000,12.68854
3,Factura,2024000004,2024-12-31,Venta Neta,Contado,Contado,35,265,U111,579,585,P004299,C123767,1,C123767-01,IGV,S/,3.77,2.0,AN001,NINGUNO,2024-12-31,19.9384,4,840.15,711.99,409.180000,0.00,0.00,409.180000,14.53040
4,Factura,2024000004,2024-12-31,Promoción,Contado,Contado,35,265,U111,579,585,P004299,C123767,1,C123767-01,EXE_IGV,S/,3.77,0.0,AN001,NINGUNO,2024-12-31,4.9846,1,181.63,0.00,0.000000,102.29,181.63,102.290000,0.00000

Columnas:
['Documento', 'Documento_ID-NEW', 'FechaEmision', 'TipoVenta', 'TerminoPago', 'TerminoPago_Resumen', 'Vendedor_ID', 'Gerencia_ID', 'UnidadNegocio_ID', 'TipoGerencia_ID', 'Procedencia_ID', 'Producto_ID-NEW', 'Cliente_ID-NEW', 'Domicilio_ID', 'Cliente_Dom_ID-NEW', 'Indicador_Impuesto', 'Moneda', 'Tipo_Cambio', 'Descuento_Porc', 'Almacen', 'Motivo_Descuento', 'FechaVencimiento', 'Galones', 'Cantidad', 'Total_con_Impuesto', 'Total_sin_Impuesto', 'Total_Costo', 'Total_Promocion', 'Total_Promocion_PV', 'Total_Total_Costo', 'Descuento']

Tipos de datos:
Documento                      object
Documento_ID-NEW                int64
FechaEmision           datetime64[ns]
TipoVenta                      object
TerminoPago                    object
TerminoPago_Resumen            object
Vendedor_ID                     int64
Gerencia_ID                     int64
UnidadNegocio_ID               object
TipoGerencia_ID                 int64
Procedencia_ID                  int64
Producto_ID-NEW                object
Cliente_ID-NEW                 object
Domicilio_ID                    int64
Cliente_Dom_ID-NEW             object
Indicador_Impuesto             object
Moneda                         object
Tipo_Cambio                   float64
Descuento_Porc                float64
Almacen                        object
Motivo_Descuento               object
FechaVencimiento       datetime64[ns]
Galones                       float64
Cantidad                        int64
Total_con_Impuesto            float64
Total_sin_Impuesto            float64
Total_Costo                   float64
Total_Promocion               float64
Total_Promocion_PV            float64
Total_Total_Costo             float64
Descuento                     float64
dtype: object

## 5. Resumen estructural

Este bloque ayuda a comparar rápidamente los tres archivos.

In [7]:
summary = []

for dataset_name, sheet_dict in datasets.items():
    for sheet_name, df in sheet_dict.items():
        summary.append({
            'dataset': dataset_name,
            'sheet': sheet_name,
            'rows': df.shape[0],
            'cols': df.shape[1],
            'missing_cells': int(df.isna().sum().sum()),
            'duplicate_rows': int(df.duplicated().sum())
        })

summary_df = pd.DataFrame(summary)
summary_df

                           dataset              sheet     rows  cols  missing_cells  duplicate_rows
0         0_PI_Dims-Deuda - ENVIAR             Deudas   454679    28         973569              69
1         0_PI_Dims-Deuda - ENVIAR       Dim_Gerencia        8     2              0               0
2         0_PI_Dims-Deuda - ENVIAR  Dim_UnidadNegocio      119     7            124               0
3         0_PI_Dims-Deuda - ENVIAR   Dim_TipoGerencia        6     2              0               0
4         0_PI_Dims-Deuda - ENVIAR    Dim_Procedencia        4     2              0               0
5         0_PI_Dims-Deuda - ENVIAR       Dim_Producto     6073     7           3706               0
6         0_PI_Dims-Deuda - ENVIAR        Dim_Cliente   167550    25         161820               0
7   0_PI_Ventas-2022-2023 - ENVIAR        Ventas_2023   873613    31         364576           11348
8   0_PI_Ventas-2022-2023 - ENVIAR        Ventas_2022   843446    31         908723            8135
9   0_PI_Ventas-2024-2025 - ENVIAR      Ventas_2025-2   671019    31          93990            2078
10  0_PI_Ventas-2024-2025 - ENVIAR      Ventas_2025-1   583137    31         108370            9278
11  0_PI_Ventas-2024-2025 - ENVIAR        Ventas_2024  1002662    31         140892           19752

## 6. Calidad de datos por dataset

In [8]:
for dataset_name, sheet_dict in datasets.items():
    print('='*90)
    print(f'CALIDAD DE DATOS: {dataset_name}')
    print('='*90)

    for sheet_name, df in sheet_dict.items():
        print(f'\nSHEET: {sheet_name}')
        quality = pd.DataFrame({
            'column': df.columns,
            'dtype': df.dtypes.astype(str).values,
            'nulls': df.isna().sum().values,
            'null_pct': (df.isna().mean().values * 100).round(2),
            'n_unique': df.nunique(dropna=True).values
        }).sort_values(by='null_pct', ascending=False)

        display(quality)

==========================================================================================
CALIDAD DE DATOS: 0_PI_Dims-Deuda - ENVIAR
==========================================================================================

SHEET: Deudas

                  column           dtype   nulls  null_pct  n_unique
21  DiasVencimientoMayor          object  371265     81.65         9
17         Fecha_UltPago  datetime64[ns]  322641     70.96       905
20          Calificacion          object  265425     58.38         7
16           TerminoPago          object    9961      2.19        12
4            Gerencia_ID         float64    3795      0.83         7
2     Cliente_Dom_ID-NEW          object     481      0.11     40331
6        TipoGerencia_ID           int64       0      0.00         1
7         Procedencia_ID           int64       0      0.00         1
3            Vendedor_ID           int64       0      0.00       417
5       UnidadNegocio_ID          object       0      0.00        74
1           Domicilio_ID          object       0      0.00        59
0         Cliente_ID-NEW          object       0      0.00     38896
11          FechaEmision  datetime64[ns]       0      0.00      1184
10         TipoDocumento          object       1      0.00         9
9       Documento_ID-NEW           int64       0      0.00    238607
8             Periodo_ID  datetime64[ns]       0      0.00        24
15                  Dias           int64       0      0.00      2268
14   TerminoPago_Resumen          object       0      0.00         2
12      FechaVencimiento  datetime64[ns]       0      0.00      1459
13       DiasVencimiento          object       0      0.00        10
19                Moneda          object       0      0.00         2
18         Actualizacion  datetime64[ns]       0      0.00        47
22     OrdenCalificacion           int64       0      0.00         8
23                 Saldo         float64       0      0.00    134889
24        MontoDocumento         float64       0      0.00    104579
25         Monto_UltPago         float64       0      0.00     27767
26            Importe_FC         float64       0      0.00       189
27              Saldo_FC         float64       0      0.00       189

SHEET: Dim_Gerencia

        column   dtype  nulls  null_pct  n_unique
0  Gerencia_ID   int64      0       0.0         8
1     Gerencia  object      0       0.0         8

SHEET: Dim_UnidadNegocio

               column   dtype  nulls  null_pct  n_unique
4               Canal  object     35     29.41         8
5            Subcanal  object     35     29.41        12
3    DescripcionPadre  object     33     27.73        28
2  GrupoUnidadNegocio  object     20     16.81        19
1       UnidadNegocio  object      1      0.84       118
0    UnidadNegocio_ID  object      0      0.00       119
6          Territorio  object      0      0.00         3

SHEET: Dim_TipoGerencia

            column   dtype  nulls  null_pct  n_unique
0  TipoGerencia_ID   int64      0       0.0         6
1     TipoGerencia  object      0       0.0         6

SHEET: Dim_Procedencia

           column   dtype  nulls  null_pct  n_unique
0  Procedencia_ID   int64      0       0.0         4
1     Procedencia  object      0       0.0         4

SHEET: Dim_Producto

            column    dtype  nulls  null_pct  n_unique
5            Linea   object   3121     51.39       141
4        Categoria   object    585      9.63        15
0  Producto_ID-NEW   object      0      0.00      6073
2    GrupoProducto   object      0      0.00        11
1     UnidadMedida   object      0      0.00        36
3           Estado   object      0      0.00         2
6         Galonaje  float64      0      0.00       357

SHEET: Dim_Cliente

                  column           dtype  nulls  null_pct  n_unique
14              Dia_Ruta          object  66945     39.96        14
6              Actividad          object  39386     23.51        19
5           Giro_Negocio          object  33605     20.06        81
21    CategoriaPotencial          object   5088      3.04         4
8              Provincia          object   3152      1.88       212
7               Distrito          object   3151      1.88      1117
9           Departamento          object   3155      1.88        45
16              Longitud          object   2463      1.47     63477
17               Latitud          object   2463      1.47     66739
11                Ubigeo          object   2269      1.35      1179
13           Vendedor_ID         float64    143      0.09       503
1           Domicilio_ID          object      0      0.00       290
4   FechaCreacionCliente  datetime64[ns]      0      0.00      1592
0         Cliente_ID-NEW          object      0      0.00    150846
2     Cliente_Dom_ID-NEW          object      0      0.00    167550
3      Cliente_Categoria          object      0      0.00         4
10                  Pais          object      0      0.00        35
15          Dias_Entrega           int64      0      0.00        13
12         Linea_Credito         float64      0      0.00       504
19         CondicionPago          object      0      0.00        23
18         Geolocalizado          object      0      0.00         2
20                Estado          object      0      0.00         2
22    TipoIdentificacion          object      0      0.00         5
23           Actualizado           int64      0      0.00         2
24                 Saldo         float64      0      0.00     10848

==========================================================================================
CALIDAD DE DATOS: 0_PI_Ventas-2022-2023 - ENVIAR
==========================================================================================

SHEET: Ventas_2023

                 column           dtype   nulls  null_pct  n_unique
20     Motivo_Descuento          object  299606     34.30         8
21     FechaVencimiento  datetime64[ns]   63976      7.32       441
11      Producto_ID-NEW          object     512      0.06      1058
19              Almacen          object     482      0.06        39
3             TipoVenta          object       0      0.00         3
1      Documento_ID-NEW           int64       0      0.00    349173
0             Documento          object       0      0.00         2
6           Vendedor_ID           int64       0      0.00       224
7           Gerencia_ID           int64       0      0.00         8
9       TipoGerencia_ID           int64       0      0.00         1
8      UnidadNegocio_ID          object       0      0.00        50
10       Procedencia_ID           int64       0      0.00         1
4           TerminoPago          object       0      0.00        15
5   TerminoPago_Resumen          object       0      0.00         2
2          FechaEmision  datetime64[ns]       0      0.00       328
14   Cliente_Dom_ID-NEW          object       0      0.00     43630
13         Domicilio_ID           int64       0      0.00        45
12       Cliente_ID-NEW          object       0      0.00     42224
15   Indicador_Impuesto          object       0      0.00         3
18       Descuento_Porc         float64       0      0.00       557
17          Tipo_Cambio         float64       0      0.00       161
16               Moneda          object       0      0.00         2
22              Galones         float64       0      0.00      3432
23             Cantidad           int64       0      0.00       719
24   Total_con_Impuesto         float64       0      0.00     67926
25   Total_sin_Impuesto         float64       0      0.00     56531
26          Total_Costo         float64       0      0.00    101263
27      Total_Promocion         float64       0      0.00     32694
28   Total_Promocion_PV         float64       0      0.00     15031
29    Total_Total_Costo         float64       0      0.00    111648
30            Descuento         float64       0      0.00     33530

SHEET: Ventas_2022

                 column           dtype   nulls  null_pct  n_unique
20     Motivo_Descuento         float64  843446    100.00         0
21     FechaVencimiento  datetime64[ns]   63910      7.58       444
11      Producto_ID-NEW          object     808      0.10      1212
19              Almacen          object     559      0.07        47
3             TipoVenta          object       0      0.00         3
1      Documento_ID-NEW           int64       0      0.00    313577
0             Documento          object       0      0.00         2
6           Vendedor_ID           int64       0      0.00       273
7           Gerencia_ID           int64       0      0.00        10
9       TipoGerencia_ID           int64       0      0.00         1
8      UnidadNegocio_ID          object       0      0.00        50
10       Procedencia_ID           int64       0      0.00         1
4           TerminoPago          object       0      0.00        21
5   TerminoPago_Resumen          object       0      0.00         2
2          FechaEmision  datetime64[ns]       0      0.00       350
14   Cliente_Dom_ID-NEW          object       0      0.00     43061
13         Domicilio_ID           int64       0      0.00        42
12       Cliente_ID-NEW          object       0      0.00     41637
15   Indicador_Impuesto          object       0      0.00         2
18       Descuento_Porc         float64       0      0.00       463
17          Tipo_Cambio         float64       0      0.00       160
16               Moneda          object       0      0.00         2
22              Galones         float64       0      0.00      4117
23             Cantidad         float64       0      0.00       811
24   Total_con_Impuesto         float64       0      0.00     72560
25   Total_sin_Impuesto         float64       0      0.00     61289
26          Total_Costo         float64       0      0.00     99414
27      Total_Promocion         float64       0      0.00     31814
28   Total_Promocion_PV         float64       0      0.00     16260
29    Total_Total_Costo         float64       0      0.00    110248
30            Descuento         float64       0      0.00     36659

==========================================================================================
CALIDAD DE DATOS: 0_PI_Ventas-2024-2025 - ENVIAR
==========================================================================================

SHEET: Ventas_2025-2

                 column           dtype  nulls  null_pct  n_unique
11      Producto_ID-NEW          object  48354      7.21       985
21     FechaVencimiento  datetime64[ns]  44866      6.69       260
19              Almacen          object    770      0.11        33
3             TipoVenta          object      0      0.00         3
4           TerminoPago          object      0      0.00        12
1      Documento_ID-NEW           int64      0      0.00    285799
0             Documento          object      0      0.00         2
6           Vendedor_ID           int64      0      0.00       243
7           Gerencia_ID           int64      0      0.00         6
9       TipoGerencia_ID           int64      0      0.00         1
8      UnidadNegocio_ID          object      0      0.00        71
10       Procedencia_ID           int64      0      0.00         1
12       Cliente_ID-NEW          object      0      0.00     45592
5   TerminoPago_Resumen          object      0      0.00         2
2          FechaEmision  datetime64[ns]      0      0.00       167
14   Cliente_Dom_ID-NEW          object      0      0.00     47206
13         Domicilio_ID          object      0      0.00        48
15   Indicador_Impuesto          object      0      0.00         3
16               Moneda          object      0      0.00         2
18       Descuento_Porc         float64      0      0.00      1667
17          Tipo_Cambio         float64      0      0.00        81
20     Motivo_Descuento          object      0      0.00         2
22              Galones         float64      0      0.00      3197
23             Cantidad           int64      0      0.00       530
24   Total_con_Impuesto         float64      0      0.00     42826
25   Total_sin_Impuesto         float64      0      0.00     37451
26          Total_Costo         float64      0      0.00     77624
27      Total_Promocion         float64      0      0.00     21031
28   Total_Promocion_PV         float64      0      0.00      6463
29    Total_Total_Costo         float64      0      0.00     84154
30            Descuento         float64      0      0.00     28077

SHEET: Ventas_2025-1

                 column           dtype  nulls  null_pct  n_unique
11      Producto_ID-NEW          object  72858     12.49       908
21     FechaVencimiento  datetime64[ns]  35302      6.05       254
19              Almacen          object    210      0.04        39
3             TipoVenta          object      0      0.00         3
4           TerminoPago          object      0      0.00        11
1      Documento_ID-NEW           int64      0      0.00    230051
0             Documento          object      0      0.00         2
6           Vendedor_ID           int64      0      0.00       235
7           Gerencia_ID           int64      0      0.00         7
9       TipoGerencia_ID           int64      0      0.00         1
8      UnidadNegocio_ID          object      0      0.00        72
10       Procedencia_ID           int64      0      0.00         1
12       Cliente_ID-NEW          object      0      0.00     42665
5   TerminoPago_Resumen          object      0      0.00         2
2          FechaEmision  datetime64[ns]      0      0.00       157
14   Cliente_Dom_ID-NEW          object      0      0.00     43986
13         Domicilio_ID           int64      0      0.00        60
15   Indicador_Impuesto          object      0      0.00         3
16               Moneda          object      0      0.00         2
18       Descuento_Porc         float64      0      0.00      1163
17          Tipo_Cambio         float64      0      0.00        90
20     Motivo_Descuento          object      0      0.00         4
22              Galones         float64      0      0.00      2996
23             Cantidad           int64      0      0.00       504
24   Total_con_Impuesto         float64      0      0.00     38288
25   Total_sin_Impuesto         float64      0      0.00     33560
26          Total_Costo         float64      0      0.00     69636
27      Total_Promocion         float64      0      0.00     18983
28   Total_Promocion_PV         float64      0      0.00      5908
29    Total_Total_Costo         float64      0      0.00     75606
30            Descuento         float64      0      0.00     23566

SHEET: Ventas_2024

                 column           dtype  nulls  null_pct  n_unique
11      Producto_ID-NEW          object  83849      8.36       856
21     FechaVencimiento  datetime64[ns]  56431      5.63       443
19              Almacen          object    606      0.06        35
3             TipoVenta          object      0      0.00         3
4           TerminoPago          object      0      0.00        15
1      Documento_ID-NEW           int64      0      0.00    405389
0             Documento          object      0      0.00         2
6           Vendedor_ID           int64      0      0.00       203
7           Gerencia_ID           int64      0      0.00         8
9       TipoGerencia_ID           int64      0      0.00         1
8      UnidadNegocio_ID          object      0      0.00        51
10       Procedencia_ID           int64      0      0.00         1
12       Cliente_ID-NEW          object      0      0.00     44035
5   TerminoPago_Resumen          object      0      0.00         2
2          FechaEmision  datetime64[ns]      0      0.00       329
14   Cliente_Dom_ID-NEW          object      0      0.00     45682
13         Domicilio_ID           int64      0      0.00        47
15   Indicador_Impuesto          object      0      0.00         3
16               Moneda          object      0      0.00         2
18       Descuento_Porc         float64      0      0.00      1166
17          Tipo_Cambio         float64      0      0.00       121
20     Motivo_Descuento          object      6      0.00         7
22              Galones         float64      0      0.00      3217
23             Cantidad           int64      0      0.00       632
24   Total_con_Impuesto         float64      0      0.00     53192
25   Total_sin_Impuesto         float64      0      0.00     45231
26          Total_Costo         float64      0      0.00    104087
27      Total_Promocion         float64      0      0.00     31391
28   Total_Promocion_PV         float64      0      0.00      9665
29    Total_Total_Costo         float64      0      0.00    113660
30            Descuento         float64      0      0.00     29398

## 7. Identificación preliminar del rol de cada archivo

- **0_PI_Ventas-2022-2023 - ENVIAR.xlsx**: contiene información transaccional de ventas por año (2022 y 2023). Su rol principal es servir como fuente histórica de comportamiento de compra.
- **0_PI_Ventas-2024-2025 - ENVIAR.xlsx**: contiene información transaccional de ventas por año y corte (2024, 2025-1 y 2025-2). Complementa la serie temporal de ventas y será parte de la base principal para construir churn.
- **0_PI_Dims-Deuda - ENVIAR.xlsx**: contiene una tabla de hechos (`Deudas`) y varias dimensiones (`Dim_Cliente`, `Dim_Producto`, `Dim_Gerencia`, etc.). Su rol principal es enriquecer el análisis con atributos del cliente, producto y situación de deuda.

### Clasificación preliminar
- Archivos de ventas: **transacciones**
- Archivo de deuda: **hechos + dimensiones**
- Unidad objetivo del proyecto: **cliente**

## 8. Criterios para definir churn

1. **¿Existe una fecha de transacción o última compra?**  
   Preliminarmente sí, ya que las ventas están organizadas por periodos anuales y semestrales, lo que sugiere la existencia de variables temporales de operación o compra. Esto debe confirmarse con la revisión de columnas.

2. **¿La unidad es cliente o transacción?**  
   La fuente principal de ventas parece estar a nivel transaccional, pero el dataset analítico final se construirá a nivel cliente.

3. **¿Se puede calcular recencia, frecuencia y monto?**  
   Sí, si las tablas de ventas contienen identificador de cliente, fecha de compra y monto vendido. Estas tres variables permitirán construir métricas RFM.

4. **¿Qué ventana de inactividad sería razonable?**  
   Como hipótesis inicial, se propone usar una ventana de **90 días sin compra** para definir churn. Esta regla podrá ajustarse según la frecuencia real de compra observada en el EDA.

### Criterio preliminar de churn
Se definirá churn como la ausencia de compras del cliente durante una ventana determinada de tiempo, usando la consolidación histórica de ventas como fuente principal.

## 9. Próximo paso

Después de este EDA inicial, el siguiente paso será construir el dataset analítico para modelado.

### Decisiones preliminares
- La base principal del proyecto será la consolidación de las hojas de ventas 2022, 2023, 2024, 2025-1 y 2025-2.
- Las columnas clave para definir churn serán las relacionadas con:
  - identificador de cliente
  - fecha de compra o fecha de operación
  - monto de venta
- El archivo de deuda se utilizará como fuente complementaria para enriquecer atributos del cliente.
- Será necesario identificar la llave común entre ventas y las dimensiones de deuda, especialmente `Dim_Cliente`.

### Siguiente notebook
El siguiente notebook será `02_data_preparation_churn.ipynb`, donde se realizará:
- la unificación de hojas de ventas
- la identificación de la llave de cliente
- la construcción de variables RFM
- la definición operativa de churn

## 10. Conclusiones del EDA

- Los archivos de ventas constituyen la fuente principal para construir la variable churn.
- La unidad de análisis objetivo será el cliente.
- Es necesario consolidar las hojas de ventas 2022–2025 en una sola tabla transaccional.
- El archivo de deuda se utilizará como fuente complementaria para enriquecer variables del cliente.
- Se deberá confirmar la llave común entre ventas y las dimensiones del archivo de deuda, especialmente `Dim_Cliente`.
- El siguiente paso será construir un dataset analítico a nivel cliente y definir churn según inactividad de compra.